id: P89764226
initial_creation_type: input
source_metadata:
  title: Tamdrin Gönpo Series
  language: bo
  description: 'Texts by and about Tamdrin Gönpo (rta mgrin mgon po):'
  volume:
    a6dd1c3fb5ec47a4810ba4ded1786cea:
      title: 'Bright Light of the Sun: A Simple Fire Offering Based on a Single Substance'
      parent: Practices
created_at: '2022-03-01T01:38:58.164209'
last_modified_at: '2022-03-01T01:38:58.164213'
